[package]
name = "pocket-relay-client"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[build-dependencies]
winres = "0.1"


[dependencies]
# Serialization and HTTP requests
reqwest = { version = "0.11.12", features = ["blocking", "json" ] }
serde = { version = "1.0", features = ["derive"] }

# Native file picker dialog
native-dialog = "0.6.3"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"

# GUI
[dependencies.iced]
version = "0.5.2"
default-features = false
features = ["svg", "image_rs", "glow"]