[package]
name = "pocket-relay-client"
version = "0.1.2"
edition = "2021"
build = "build.rs"
license = "MIT"
description = "Client application for the Pocket Relay server"
readme = "README.md"
authors = ["Jacobtread <jacobtread@gmail.com>"]
keywords = ["EA", "PocketRelay", "MassEffect"]

[build-dependencies]
winres = "0.1"

[dependencies]
# Serialization and HTTP requests
reqwest = { version = "0.11", features = ["blocking", "json" ] }
serde = { version = "1", features = ["derive"] }

# Native file picker dialog
native-dialog = "0.6.3"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"

# GUI
[dependencies.iced]
version = "0.6"
default-features = false
features = ["svg", "image_rs", "glow"]